<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'belanur\\validation\\abstractvalidator' => '/validation/AbstractValidator.php',
                'belanur\\validation\\notemptyvalidator' => '/validation/valueValidators/NotEmptyValidator.php',
                'belanur\\validation\\registrationvalidator' => '/validation/RegistrationValidator.php',
                'belanur\\validation\\validatorinterface' => '/validation/ValidatorInterface.php',
                'belanur\\validation\\valuevalidatorinterface' => '/validation/valueValidators/ValueValidatorInterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd